#!/usr/bin/env python3
"""
prep_SH0ES22_partial.py
Extract the SN-only rows from the full SH0ES distance ladder matrices.

Uses SH0ES_y_labels.csv (index column = original FITS row number, generated by
check_ylabels.py) to select:

  * "standard calibrator" SNe  -- 3-part labels with a known Cepheid host
  * "standard Hubble-flow" SNe -- 2-part labels (no host galaxy)

MW parallax anchor rows (CID == 'MW') are excluded.

Outputs
-------
SH0ES22_partial_y.npy      : (N,)   SN apparent-magnitude observations
SH0ES22_partial_C.npy      : (N,N)  covariance block for selected SN rows
SH0ES22_partial_labels.csv : row metadata -- label, type (cal/hf), host galaxy name
"""

import numpy as np
import pandas as pd
from astropy.io import fits

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
Y_PATH       = 'ally_shoes_ceph_topantheonwt6.0_112221.fits'
C_PATH       = 'allc_shoes_ceph_topantheonwt6.0_112221.fits'
YLABELS_PATH = 'SH0ES_y_labels.csv'

OUT_Y      = 'custom_y.npy'
OUT_C      = 'custom_C.npy'
OUT_LABELS = 'custom_labels.csv'

# ---------------------------------------------------------------------------
# Load pre-classified SN labels
# The index column contains the original FITS row number for each SN.
# ---------------------------------------------------------------------------
print('Loading SN labels ...')
yl = pd.read_csv(YLABELS_PATH, index_col=0)

# Calibrator SNe: 3-part labels with a known Cepheid host galaxy
cal_mask = yl['calib_host'].notna()
# Hubble-flow SNe: 2-part labels, no host; exclude MW parallax anchor rows
hf_mask  = yl['calib_host'].isna() & (yl['CID'] != 'MW')

sn_yl = yl[cal_mask | hf_mask].copy()
sn_yl['type'] = 'HF'
sn_yl.loc[sn_yl['calib_host'].notna(), 'type'] = 'CAL'

selected_idx = sn_yl.index.values   # original FITS indices

n_cal = (sn_yl['type'] == 'CAL').sum()
n_hf  = (sn_yl['type'] == 'HF').sum()
print(f'Selected {len(selected_idx)} SN rows  ({n_cal} calibrators, {n_hf} Hubble-flow)')

# ---------------------------------------------------------------------------
# Extract sub-matrices using the correct original indices
# ---------------------------------------------------------------------------
print('Loading FITS data ...')
y = fits.open(Y_PATH)[0].data.astype(float)
C = fits.open(C_PATH)[0].data.astype(float)

y_trunc = y[selected_idx]
C_trunc = C[np.ix_(selected_idx, selected_idx)]

labels_df = pd.DataFrame({
    'orig_index': selected_idx,
    'label'     : sn_yl['label'].values,
    'type'      : sn_yl['type'].values,
    'host'      : sn_yl['calib_host'].fillna('').values,
})

cal_hosts = list(dict.fromkeys(labels_df.loc[labels_df['type'] == 'CAL', 'host']))
print(f'\nCalibrator hosts ({len(cal_hosts)}):')
for h in cal_hosts:
    n = (labels_df['host'] == h).sum()
    print(f'  {h:20s}  {n} SN obs')

# ---------------------------------------------------------------------------
# Save
# ---------------------------------------------------------------------------
np.save(OUT_Y, y_trunc)
np.save(OUT_C, C_trunc)
labels_df.to_csv(OUT_LABELS, index=False)

print(f'\nSaved:')
print(f'  {OUT_Y}       shape {y_trunc.shape}')
print(f'  {OUT_C}       shape {C_trunc.shape}')
print(f'  {OUT_LABELS}  {len(labels_df)} rows')

# ---------------------------------------------------------------------------
# Sanity check: reproduce SH0ES result using lstsq solution
# ---------------------------------------------------------------------------
q = np.loadtxt('lstsq_results.txt', usecols=0)
M_B_lstsq = q[42]          # parameter 42 = M_B  ≈ -19.24
H0_lstsq  = 10 ** (q[46] / 5)   # parameter 46 = 5*log10(H0)

implied = {}
for _, row in labels_df[labels_df['type'] == 'CAL'].iterrows():
    implied.setdefault(row['host'], []).append(y[row['orig_index']] - M_B_lstsq)

print(f'\nSH0ES lstsq reference values:')
print(f'  M_B  = {M_B_lstsq:.4f}')
print(f'  H0   = {H0_lstsq:.4f}  (from q[46] = {q[46]:.4f})')
print(f'\nImplied host μ from SH0ES SN data (for validation only — NOT true Cepheid distances):')
for h in cal_hosts:
    vals = implied[h]
    print(f'  {h:20s}  μ = {np.mean(vals):.4f} ± {np.std(vals):.4f}  ({len(vals)} obs)')
